---
apiVersion: "v1"
kind: "List"
items:

  - apiVersion: "v1"
    kind: "ReplicationController"
    metadata:
      name: "te-mb-replication"
      namespace: "taf-te"
      labels:
        name: "te-mb-replication"
    spec:
      replicas: 1
      template:
        metadata:
          name: "te-mb-tpl"
          labels:
            name: "te-mb-tpl"
        spec:
          imagePullSecrets:
            - name: "armdocker.rnd.ericsson.se"
          containers:
            - name: "taf-te-message-bus"
              image: "armdocker.rnd.ericsson.se/proj_taf_te/taf_te_message_bus:2.0"
              ports:
                - containerPort: 15672
                - containerPort: 5672
