---
apiVersion: "v1"
kind: "List"
items:
  - apiVersion: "v1"
    kind: "Service"
    metadata:
      name: "te-mb-service"
      namespace: "taf-te"
    spec:
      type: "NodePort"
      selector:
        name: "te-mb-tpl"
      ports:
        -
          name: "web"
          port: 15672
          targetPort: 15672
          nodePort: 30006
          protocol: "TCP"
        -
          name: "messages"
          port: 5672
          targetPort: 5672
          protocol: "TCP"
          nodePort: 30007
