package com.ericsson.cifwk.taf.executor.node;

import org.apache.commons.io.FileUtils;

import java.io.File;
import java.io.FileFilter;
import java.io.IOException;

/**
 * Filters failed and partial test suites generated by
 * {@link com.ericsson.cifwk.taf.FakeSuiteGenerator}.
 * Expected to be used only on Allure report output directories.
 */
public class AllureFakeSuiteFileFilter implements FileFilter {

    /**
     * Based on the taf-allure-suite-generator templates for failed/partial execution
     */
    private static final String FAKE_SUITE_MARKER = "<name>Failed to get executed</name>";

    @Override
    public boolean accept(File pathname) {
        try {
            String contents = FileUtils.readFileToString(pathname);
            return contents.contains(FAKE_SUITE_MARKER);
        } catch (IOException e) {
            throw new RuntimeException("Could not read file to string: " + pathname, e);
        }
    }
}
