/**
 * This class is generated by jOOQ
 */
package com.ericsson.cifwk.taf.metrics.jooq;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>taf_performance</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<com.ericsson.cifwk.taf.metrics.jooq.tables.records.SamplesRecord, java.lang.Long> IDENTITY_SAMPLES = Identities0.IDENTITY_SAMPLES;
	public static final org.jooq.Identity<com.ericsson.cifwk.taf.metrics.jooq.tables.records.SampleDataRecord, java.lang.Long> IDENTITY_SAMPLE_DATA = Identities0.IDENTITY_SAMPLE_DATA;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<com.ericsson.cifwk.taf.metrics.jooq.tables.records.ExecutionsRecord> KEY_EXECUTIONS_PRIMARY = UniqueKeys0.KEY_EXECUTIONS_PRIMARY;
	public static final org.jooq.UniqueKey<com.ericsson.cifwk.taf.metrics.jooq.tables.records.ExecutionsRecord> KEY_EXECUTIONS_ID_UNIQUE = UniqueKeys0.KEY_EXECUTIONS_ID_UNIQUE;
	public static final org.jooq.UniqueKey<com.ericsson.cifwk.taf.metrics.jooq.tables.records.ExecutionsRecord> KEY_EXECUTIONS_NAME_UNIQUE = UniqueKeys0.KEY_EXECUTIONS_NAME_UNIQUE;
	public static final org.jooq.UniqueKey<com.ericsson.cifwk.taf.metrics.jooq.tables.records.SamplesRecord> KEY_SAMPLES_PRIMARY = UniqueKeys0.KEY_SAMPLES_PRIMARY;
	public static final org.jooq.UniqueKey<com.ericsson.cifwk.taf.metrics.jooq.tables.records.SampleDataRecord> KEY_SAMPLE_DATA_PRIMARY = UniqueKeys0.KEY_SAMPLE_DATA_PRIMARY;
	public static final org.jooq.UniqueKey<com.ericsson.cifwk.taf.metrics.jooq.tables.records.TestCasesRecord> KEY_TEST_CASES_PRIMARY = UniqueKeys0.KEY_TEST_CASES_PRIMARY;
	public static final org.jooq.UniqueKey<com.ericsson.cifwk.taf.metrics.jooq.tables.records.TestCasesRecord> KEY_TEST_CASES_NAME_UNIQUE = UniqueKeys0.KEY_TEST_CASES_NAME_UNIQUE;
	public static final org.jooq.UniqueKey<com.ericsson.cifwk.taf.metrics.jooq.tables.records.TestSuitesRecord> KEY_TEST_SUITES_PRIMARY = UniqueKeys0.KEY_TEST_SUITES_PRIMARY;
	public static final org.jooq.UniqueKey<com.ericsson.cifwk.taf.metrics.jooq.tables.records.TestSuitesRecord> KEY_TEST_SUITES_NAME_UNIQUE = UniqueKeys0.KEY_TEST_SUITES_NAME_UNIQUE;
	public static final org.jooq.UniqueKey<com.ericsson.cifwk.taf.metrics.jooq.tables.records.TimeRecord> KEY_TIME_PRIMARY = UniqueKeys0.KEY_TIME_PRIMARY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.ForeignKey<com.ericsson.cifwk.taf.metrics.jooq.tables.records.SamplesRecord, com.ericsson.cifwk.taf.metrics.jooq.tables.records.TimeRecord> FK_SAMPLES_TIME = ForeignKeys0.FK_SAMPLES_TIME;
	public static final org.jooq.ForeignKey<com.ericsson.cifwk.taf.metrics.jooq.tables.records.SamplesRecord, com.ericsson.cifwk.taf.metrics.jooq.tables.records.TestCasesRecord> FK_SAMPLES_TEST_CASES1 = ForeignKeys0.FK_SAMPLES_TEST_CASES1;
	public static final org.jooq.ForeignKey<com.ericsson.cifwk.taf.metrics.jooq.tables.records.SampleDataRecord, com.ericsson.cifwk.taf.metrics.jooq.tables.records.SamplesRecord> FK_SAMPLE_DATA_SAMPLES1 = ForeignKeys0.FK_SAMPLE_DATA_SAMPLES1;
	public static final org.jooq.ForeignKey<com.ericsson.cifwk.taf.metrics.jooq.tables.records.TestCasesRecord, com.ericsson.cifwk.taf.metrics.jooq.tables.records.TestSuitesRecord> FK_TEST_CASES_TEST_SUITES1 = ForeignKeys0.FK_TEST_CASES_TEST_SUITES1;
	public static final org.jooq.ForeignKey<com.ericsson.cifwk.taf.metrics.jooq.tables.records.TestSuitesRecord, com.ericsson.cifwk.taf.metrics.jooq.tables.records.ExecutionsRecord> FK_TEST_SUITES_EXECUTIONS1 = ForeignKeys0.FK_TEST_SUITES_EXECUTIONS1;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<com.ericsson.cifwk.taf.metrics.jooq.tables.records.SamplesRecord, java.lang.Long> IDENTITY_SAMPLES = createIdentity(com.ericsson.cifwk.taf.metrics.jooq.tables.Samples.SAMPLES, com.ericsson.cifwk.taf.metrics.jooq.tables.Samples.SAMPLES.ID);
		public static org.jooq.Identity<com.ericsson.cifwk.taf.metrics.jooq.tables.records.SampleDataRecord, java.lang.Long> IDENTITY_SAMPLE_DATA = createIdentity(com.ericsson.cifwk.taf.metrics.jooq.tables.SampleData.SAMPLE_DATA, com.ericsson.cifwk.taf.metrics.jooq.tables.SampleData.SAMPLE_DATA.ID);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<com.ericsson.cifwk.taf.metrics.jooq.tables.records.ExecutionsRecord> KEY_EXECUTIONS_PRIMARY = createUniqueKey(com.ericsson.cifwk.taf.metrics.jooq.tables.Executions.EXECUTIONS, com.ericsson.cifwk.taf.metrics.jooq.tables.Executions.EXECUTIONS.ID);
		public static final org.jooq.UniqueKey<com.ericsson.cifwk.taf.metrics.jooq.tables.records.ExecutionsRecord> KEY_EXECUTIONS_ID_UNIQUE = createUniqueKey(com.ericsson.cifwk.taf.metrics.jooq.tables.Executions.EXECUTIONS, com.ericsson.cifwk.taf.metrics.jooq.tables.Executions.EXECUTIONS.ID);
		public static final org.jooq.UniqueKey<com.ericsson.cifwk.taf.metrics.jooq.tables.records.ExecutionsRecord> KEY_EXECUTIONS_NAME_UNIQUE = createUniqueKey(com.ericsson.cifwk.taf.metrics.jooq.tables.Executions.EXECUTIONS, com.ericsson.cifwk.taf.metrics.jooq.tables.Executions.EXECUTIONS.NAME);
		public static final org.jooq.UniqueKey<com.ericsson.cifwk.taf.metrics.jooq.tables.records.SamplesRecord> KEY_SAMPLES_PRIMARY = createUniqueKey(com.ericsson.cifwk.taf.metrics.jooq.tables.Samples.SAMPLES, com.ericsson.cifwk.taf.metrics.jooq.tables.Samples.SAMPLES.ID);
		public static final org.jooq.UniqueKey<com.ericsson.cifwk.taf.metrics.jooq.tables.records.SampleDataRecord> KEY_SAMPLE_DATA_PRIMARY = createUniqueKey(com.ericsson.cifwk.taf.metrics.jooq.tables.SampleData.SAMPLE_DATA, com.ericsson.cifwk.taf.metrics.jooq.tables.SampleData.SAMPLE_DATA.ID);
		public static final org.jooq.UniqueKey<com.ericsson.cifwk.taf.metrics.jooq.tables.records.TestCasesRecord> KEY_TEST_CASES_PRIMARY = createUniqueKey(com.ericsson.cifwk.taf.metrics.jooq.tables.TestCases.TEST_CASES, com.ericsson.cifwk.taf.metrics.jooq.tables.TestCases.TEST_CASES.ID);
		public static final org.jooq.UniqueKey<com.ericsson.cifwk.taf.metrics.jooq.tables.records.TestCasesRecord> KEY_TEST_CASES_NAME_UNIQUE = createUniqueKey(com.ericsson.cifwk.taf.metrics.jooq.tables.TestCases.TEST_CASES, com.ericsson.cifwk.taf.metrics.jooq.tables.TestCases.TEST_CASES.NAME);
		public static final org.jooq.UniqueKey<com.ericsson.cifwk.taf.metrics.jooq.tables.records.TestSuitesRecord> KEY_TEST_SUITES_PRIMARY = createUniqueKey(com.ericsson.cifwk.taf.metrics.jooq.tables.TestSuites.TEST_SUITES, com.ericsson.cifwk.taf.metrics.jooq.tables.TestSuites.TEST_SUITES.ID);
		public static final org.jooq.UniqueKey<com.ericsson.cifwk.taf.metrics.jooq.tables.records.TestSuitesRecord> KEY_TEST_SUITES_NAME_UNIQUE = createUniqueKey(com.ericsson.cifwk.taf.metrics.jooq.tables.TestSuites.TEST_SUITES, com.ericsson.cifwk.taf.metrics.jooq.tables.TestSuites.TEST_SUITES.NAME);
		public static final org.jooq.UniqueKey<com.ericsson.cifwk.taf.metrics.jooq.tables.records.TimeRecord> KEY_TIME_PRIMARY = createUniqueKey(com.ericsson.cifwk.taf.metrics.jooq.tables.Time.TIME, com.ericsson.cifwk.taf.metrics.jooq.tables.Time.TIME.ID);
	}

	private static class ForeignKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.ForeignKey<com.ericsson.cifwk.taf.metrics.jooq.tables.records.SamplesRecord, com.ericsson.cifwk.taf.metrics.jooq.tables.records.TimeRecord> FK_SAMPLES_TIME = createForeignKey(com.ericsson.cifwk.taf.metrics.jooq.Keys.KEY_TIME_PRIMARY, com.ericsson.cifwk.taf.metrics.jooq.tables.Samples.SAMPLES, com.ericsson.cifwk.taf.metrics.jooq.tables.Samples.SAMPLES.TIME_ID);
		public static final org.jooq.ForeignKey<com.ericsson.cifwk.taf.metrics.jooq.tables.records.SamplesRecord, com.ericsson.cifwk.taf.metrics.jooq.tables.records.TestCasesRecord> FK_SAMPLES_TEST_CASES1 = createForeignKey(com.ericsson.cifwk.taf.metrics.jooq.Keys.KEY_TEST_CASES_PRIMARY, com.ericsson.cifwk.taf.metrics.jooq.tables.Samples.SAMPLES, com.ericsson.cifwk.taf.metrics.jooq.tables.Samples.SAMPLES.TEST_CASE_ID);
		public static final org.jooq.ForeignKey<com.ericsson.cifwk.taf.metrics.jooq.tables.records.SampleDataRecord, com.ericsson.cifwk.taf.metrics.jooq.tables.records.SamplesRecord> FK_SAMPLE_DATA_SAMPLES1 = createForeignKey(com.ericsson.cifwk.taf.metrics.jooq.Keys.KEY_SAMPLES_PRIMARY, com.ericsson.cifwk.taf.metrics.jooq.tables.SampleData.SAMPLE_DATA, com.ericsson.cifwk.taf.metrics.jooq.tables.SampleData.SAMPLE_DATA.SAMPLE_ID);
		public static final org.jooq.ForeignKey<com.ericsson.cifwk.taf.metrics.jooq.tables.records.TestCasesRecord, com.ericsson.cifwk.taf.metrics.jooq.tables.records.TestSuitesRecord> FK_TEST_CASES_TEST_SUITES1 = createForeignKey(com.ericsson.cifwk.taf.metrics.jooq.Keys.KEY_TEST_SUITES_PRIMARY, com.ericsson.cifwk.taf.metrics.jooq.tables.TestCases.TEST_CASES, com.ericsson.cifwk.taf.metrics.jooq.tables.TestCases.TEST_CASES.TEST_SUITE_ID);
		public static final org.jooq.ForeignKey<com.ericsson.cifwk.taf.metrics.jooq.tables.records.TestSuitesRecord, com.ericsson.cifwk.taf.metrics.jooq.tables.records.ExecutionsRecord> FK_TEST_SUITES_EXECUTIONS1 = createForeignKey(com.ericsson.cifwk.taf.metrics.jooq.Keys.KEY_EXECUTIONS_PRIMARY, com.ericsson.cifwk.taf.metrics.jooq.tables.TestSuites.TEST_SUITES, com.ericsson.cifwk.taf.metrics.jooq.tables.TestSuites.TEST_SUITES.EXECUTION_ID);
	}
}
