/**
 * This class is generated by jOOQ
 */
package com.ericsson.cifwk.taf.metrics.jooq;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in taf_performance
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table taf_performance.executions
	 */
	public static final com.ericsson.cifwk.taf.metrics.jooq.tables.Executions EXECUTIONS = com.ericsson.cifwk.taf.metrics.jooq.tables.Executions.EXECUTIONS;

	/**
	 * The table taf_performance.samples
	 */
	public static final com.ericsson.cifwk.taf.metrics.jooq.tables.Samples SAMPLES = com.ericsson.cifwk.taf.metrics.jooq.tables.Samples.SAMPLES;

	/**
	 * The table taf_performance.sample_data
	 */
	public static final com.ericsson.cifwk.taf.metrics.jooq.tables.SampleData SAMPLE_DATA = com.ericsson.cifwk.taf.metrics.jooq.tables.SampleData.SAMPLE_DATA;

	/**
	 * The table taf_performance.test_cases
	 */
	public static final com.ericsson.cifwk.taf.metrics.jooq.tables.TestCases TEST_CASES = com.ericsson.cifwk.taf.metrics.jooq.tables.TestCases.TEST_CASES;

	/**
	 * The table taf_performance.test_suites
	 */
	public static final com.ericsson.cifwk.taf.metrics.jooq.tables.TestSuites TEST_SUITES = com.ericsson.cifwk.taf.metrics.jooq.tables.TestSuites.TEST_SUITES;

	/**
	 * The table taf_performance.time
	 */
	public static final com.ericsson.cifwk.taf.metrics.jooq.tables.Time TIME = com.ericsson.cifwk.taf.metrics.jooq.tables.Time.TIME;
}
