/**
 * This class is generated by jOOQ
 */
package com.ericsson.cifwk.taf.metrics.jooq;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TafPerformance extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = -1668668478;

	/**
	 * The singleton instance of <code>taf_performance</code>
	 */
	public static final TafPerformance TAF_PERFORMANCE = new TafPerformance();

	/**
	 * No further instances allowed
	 */
	private TafPerformance() {
		super("taf_performance");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			com.ericsson.cifwk.taf.metrics.jooq.tables.Executions.EXECUTIONS,
			com.ericsson.cifwk.taf.metrics.jooq.tables.Samples.SAMPLES,
			com.ericsson.cifwk.taf.metrics.jooq.tables.SampleData.SAMPLE_DATA,
			com.ericsson.cifwk.taf.metrics.jooq.tables.TestCases.TEST_CASES,
			com.ericsson.cifwk.taf.metrics.jooq.tables.TestSuites.TEST_SUITES,
			com.ericsson.cifwk.taf.metrics.jooq.tables.Time.TIME);
	}
}
