/**
 * This class is generated by jOOQ
 */
package com.ericsson.cifwk.taf.metrics.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SamplesRecord extends org.jooq.impl.UpdatableRecordImpl<com.ericsson.cifwk.taf.metrics.jooq.tables.records.SamplesRecord> implements org.jooq.Record14<java.lang.Long, java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Long, java.lang.Integer, java.lang.Byte, java.lang.Integer, java.lang.Integer, java.lang.Long, java.sql.Timestamp, java.lang.Long> {

	private static final long serialVersionUID = 570554605;

	/**
	 * Setter for <code>taf_performance.samples.id</code>.
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>taf_performance.samples.id</code>.
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>taf_performance.samples.thread_id</code>.
	 */
	public void setThreadId(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>taf_performance.samples.thread_id</code>.
	 */
	public java.lang.Long getThreadId() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>taf_performance.samples.vuser_id</code>.
	 */
	public void setVuserId(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>taf_performance.samples.vuser_id</code>.
	 */
	public java.lang.String getVuserId() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>taf_performance.samples.protocol</code>.
	 */
	public void setProtocol(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>taf_performance.samples.protocol</code>.
	 */
	public java.lang.String getProtocol() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>taf_performance.samples.target</code>.
	 */
	public void setTarget(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>taf_performance.samples.target</code>.
	 */
	public java.lang.String getTarget() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>taf_performance.samples.request_type</code>.
	 */
	public void setRequestType(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>taf_performance.samples.request_type</code>.
	 */
	public java.lang.String getRequestType() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>taf_performance.samples.request_size</code>.
	 */
	public void setRequestSize(java.lang.Long value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>taf_performance.samples.request_size</code>.
	 */
	public java.lang.Long getRequestSize() {
		return (java.lang.Long) getValue(6);
	}

	/**
	 * Setter for <code>taf_performance.samples.response_code</code>.
	 */
	public void setResponseCode(java.lang.Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>taf_performance.samples.response_code</code>.
	 */
	public java.lang.Integer getResponseCode() {
		return (java.lang.Integer) getValue(7);
	}

	/**
	 * Setter for <code>taf_performance.samples.success</code>.
	 */
	public void setSuccess(java.lang.Byte value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>taf_performance.samples.success</code>.
	 */
	public java.lang.Byte getSuccess() {
		return (java.lang.Byte) getValue(8);
	}

	/**
	 * Setter for <code>taf_performance.samples.response_time</code>.
	 */
	public void setResponseTime(java.lang.Integer value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>taf_performance.samples.response_time</code>.
	 */
	public java.lang.Integer getResponseTime() {
		return (java.lang.Integer) getValue(9);
	}

	/**
	 * Setter for <code>taf_performance.samples.latency</code>.
	 */
	public void setLatency(java.lang.Integer value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>taf_performance.samples.latency</code>.
	 */
	public java.lang.Integer getLatency() {
		return (java.lang.Integer) getValue(10);
	}

	/**
	 * Setter for <code>taf_performance.samples.response_size</code>.
	 */
	public void setResponseSize(java.lang.Long value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>taf_performance.samples.response_size</code>.
	 */
	public java.lang.Long getResponseSize() {
		return (java.lang.Long) getValue(11);
	}

	/**
	 * Setter for <code>taf_performance.samples.time_id</code>.
	 */
	public void setTimeId(java.sql.Timestamp value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>taf_performance.samples.time_id</code>.
	 */
	public java.sql.Timestamp getTimeId() {
		return (java.sql.Timestamp) getValue(12);
	}

	/**
	 * Setter for <code>taf_performance.samples.test_case_id</code>.
	 */
	public void setTestCaseId(java.lang.Long value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>taf_performance.samples.test_case_id</code>.
	 */
	public java.lang.Long getTestCaseId() {
		return (java.lang.Long) getValue(13);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record14 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row14<java.lang.Long, java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Long, java.lang.Integer, java.lang.Byte, java.lang.Integer, java.lang.Integer, java.lang.Long, java.sql.Timestamp, java.lang.Long> fieldsRow() {
		return (org.jooq.Row14) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row14<java.lang.Long, java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Long, java.lang.Integer, java.lang.Byte, java.lang.Integer, java.lang.Integer, java.lang.Long, java.sql.Timestamp, java.lang.Long> valuesRow() {
		return (org.jooq.Row14) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.ericsson.cifwk.taf.metrics.jooq.tables.Samples.SAMPLES.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return com.ericsson.cifwk.taf.metrics.jooq.tables.Samples.SAMPLES.THREAD_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.ericsson.cifwk.taf.metrics.jooq.tables.Samples.SAMPLES.VUSER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.ericsson.cifwk.taf.metrics.jooq.tables.Samples.SAMPLES.PROTOCOL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.ericsson.cifwk.taf.metrics.jooq.tables.Samples.SAMPLES.TARGET;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.ericsson.cifwk.taf.metrics.jooq.tables.Samples.SAMPLES.REQUEST_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field7() {
		return com.ericsson.cifwk.taf.metrics.jooq.tables.Samples.SAMPLES.REQUEST_SIZE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field8() {
		return com.ericsson.cifwk.taf.metrics.jooq.tables.Samples.SAMPLES.RESPONSE_CODE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field9() {
		return com.ericsson.cifwk.taf.metrics.jooq.tables.Samples.SAMPLES.SUCCESS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field10() {
		return com.ericsson.cifwk.taf.metrics.jooq.tables.Samples.SAMPLES.RESPONSE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field11() {
		return com.ericsson.cifwk.taf.metrics.jooq.tables.Samples.SAMPLES.LATENCY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field12() {
		return com.ericsson.cifwk.taf.metrics.jooq.tables.Samples.SAMPLES.RESPONSE_SIZE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field13() {
		return com.ericsson.cifwk.taf.metrics.jooq.tables.Samples.SAMPLES.TIME_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field14() {
		return com.ericsson.cifwk.taf.metrics.jooq.tables.Samples.SAMPLES.TEST_CASE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getThreadId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getVuserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getProtocol();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getTarget();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getRequestType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value7() {
		return getRequestSize();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value8() {
		return getResponseCode();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value9() {
		return getSuccess();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value10() {
		return getResponseTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value11() {
		return getLatency();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value12() {
		return getResponseSize();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value13() {
		return getTimeId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value14() {
		return getTestCaseId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SamplesRecord value1(java.lang.Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SamplesRecord value2(java.lang.Long value) {
		setThreadId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SamplesRecord value3(java.lang.String value) {
		setVuserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SamplesRecord value4(java.lang.String value) {
		setProtocol(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SamplesRecord value5(java.lang.String value) {
		setTarget(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SamplesRecord value6(java.lang.String value) {
		setRequestType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SamplesRecord value7(java.lang.Long value) {
		setRequestSize(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SamplesRecord value8(java.lang.Integer value) {
		setResponseCode(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SamplesRecord value9(java.lang.Byte value) {
		setSuccess(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SamplesRecord value10(java.lang.Integer value) {
		setResponseTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SamplesRecord value11(java.lang.Integer value) {
		setLatency(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SamplesRecord value12(java.lang.Long value) {
		setResponseSize(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SamplesRecord value13(java.sql.Timestamp value) {
		setTimeId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SamplesRecord value14(java.lang.Long value) {
		setTestCaseId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SamplesRecord values(java.lang.Long value1, java.lang.Long value2, java.lang.String value3, java.lang.String value4, java.lang.String value5, java.lang.String value6, java.lang.Long value7, java.lang.Integer value8, java.lang.Byte value9, java.lang.Integer value10, java.lang.Integer value11, java.lang.Long value12, java.sql.Timestamp value13, java.lang.Long value14) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SamplesRecord
	 */
	public SamplesRecord() {
		super(com.ericsson.cifwk.taf.metrics.jooq.tables.Samples.SAMPLES);
	}

	/**
	 * Create a detached, initialised SamplesRecord
	 */
	public SamplesRecord(java.lang.Long id, java.lang.Long threadId, java.lang.String vuserId, java.lang.String protocol, java.lang.String target, java.lang.String requestType, java.lang.Long requestSize, java.lang.Integer responseCode, java.lang.Byte success, java.lang.Integer responseTime, java.lang.Integer latency, java.lang.Long responseSize, java.sql.Timestamp timeId, java.lang.Long testCaseId) {
		super(com.ericsson.cifwk.taf.metrics.jooq.tables.Samples.SAMPLES);

		setValue(0, id);
		setValue(1, threadId);
		setValue(2, vuserId);
		setValue(3, protocol);
		setValue(4, target);
		setValue(5, requestType);
		setValue(6, requestSize);
		setValue(7, responseCode);
		setValue(8, success);
		setValue(9, responseTime);
		setValue(10, latency);
		setValue(11, responseSize);
		setValue(12, timeId);
		setValue(13, testCaseId);
	}
}
