/**
 * This class is generated by jOOQ
 */
package com.ericsson.cifwk.taf.metrics.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TestSuitesRecord extends org.jooq.impl.UpdatableRecordImpl<com.ericsson.cifwk.taf.metrics.jooq.tables.records.TestSuitesRecord> implements org.jooq.Record3<java.lang.Long, java.lang.String, java.lang.Long> {

	private static final long serialVersionUID = -1675348141;

	/**
	 * Setter for <code>taf_performance.test_suites.id</code>.
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>taf_performance.test_suites.id</code>.
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>taf_performance.test_suites.name</code>.
	 */
	public void setName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>taf_performance.test_suites.name</code>.
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>taf_performance.test_suites.execution_id</code>.
	 */
	public void setExecutionId(java.lang.Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>taf_performance.test_suites.execution_id</code>.
	 */
	public java.lang.Long getExecutionId() {
		return (java.lang.Long) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Long, java.lang.String, java.lang.Long> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Long, java.lang.String, java.lang.Long> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.ericsson.cifwk.taf.metrics.jooq.tables.TestSuites.TEST_SUITES.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.ericsson.cifwk.taf.metrics.jooq.tables.TestSuites.TEST_SUITES.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field3() {
		return com.ericsson.cifwk.taf.metrics.jooq.tables.TestSuites.TEST_SUITES.EXECUTION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value3() {
		return getExecutionId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TestSuitesRecord value1(java.lang.Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TestSuitesRecord value2(java.lang.String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TestSuitesRecord value3(java.lang.Long value) {
		setExecutionId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TestSuitesRecord values(java.lang.Long value1, java.lang.String value2, java.lang.Long value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TestSuitesRecord
	 */
	public TestSuitesRecord() {
		super(com.ericsson.cifwk.taf.metrics.jooq.tables.TestSuites.TEST_SUITES);
	}

	/**
	 * Create a detached, initialised TestSuitesRecord
	 */
	public TestSuitesRecord(java.lang.Long id, java.lang.String name, java.lang.Long executionId) {
		super(com.ericsson.cifwk.taf.metrics.jooq.tables.TestSuites.TEST_SUITES);

		setValue(0, id);
		setValue(1, name);
		setValue(2, executionId);
	}
}
