/**
 * This class is generated by jOOQ
 */
package com.ericsson.cifwk.taf.metrics.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TimeRecord extends org.jooq.impl.UpdatableRecordImpl<com.ericsson.cifwk.taf.metrics.jooq.tables.records.TimeRecord> implements org.jooq.Record4<java.sql.Timestamp, java.sql.Date, java.lang.Integer, java.lang.Integer> {

	private static final long serialVersionUID = -424453487;

	/**
	 * Setter for <code>taf_performance.time.id</code>.
	 */
	public void setId(java.sql.Timestamp value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>taf_performance.time.id</code>.
	 */
	public java.sql.Timestamp getId() {
		return (java.sql.Timestamp) getValue(0);
	}

	/**
	 * Setter for <code>taf_performance.time.day</code>.
	 */
	public void setDay(java.sql.Date value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>taf_performance.time.day</code>.
	 */
	public java.sql.Date getDay() {
		return (java.sql.Date) getValue(1);
	}

	/**
	 * Setter for <code>taf_performance.time.hour</code>.
	 */
	public void setHour(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>taf_performance.time.hour</code>.
	 */
	public java.lang.Integer getHour() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>taf_performance.time.minute</code>.
	 */
	public void setMinute(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>taf_performance.time.minute</code>.
	 */
	public java.lang.Integer getMinute() {
		return (java.lang.Integer) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.sql.Timestamp> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.sql.Timestamp, java.sql.Date, java.lang.Integer, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.sql.Timestamp, java.sql.Date, java.lang.Integer, java.lang.Integer> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field1() {
		return com.ericsson.cifwk.taf.metrics.jooq.tables.Time.TIME.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field2() {
		return com.ericsson.cifwk.taf.metrics.jooq.tables.Time.TIME.DAY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return com.ericsson.cifwk.taf.metrics.jooq.tables.Time.TIME.HOUR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return com.ericsson.cifwk.taf.metrics.jooq.tables.Time.TIME.MINUTE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value2() {
		return getDay();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getHour();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getMinute();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TimeRecord value1(java.sql.Timestamp value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TimeRecord value2(java.sql.Date value) {
		setDay(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TimeRecord value3(java.lang.Integer value) {
		setHour(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TimeRecord value4(java.lang.Integer value) {
		setMinute(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TimeRecord values(java.sql.Timestamp value1, java.sql.Date value2, java.lang.Integer value3, java.lang.Integer value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TimeRecord
	 */
	public TimeRecord() {
		super(com.ericsson.cifwk.taf.metrics.jooq.tables.Time.TIME);
	}

	/**
	 * Create a detached, initialised TimeRecord
	 */
	public TimeRecord(java.sql.Timestamp id, java.sql.Date day, java.lang.Integer hour, java.lang.Integer minute) {
		super(com.ericsson.cifwk.taf.metrics.jooq.tables.Time.TIME);

		setValue(0, id);
		setValue(1, day);
		setValue(2, hour);
		setValue(3, minute);
	}
}
