---
apiVersion: "v1"
kind: "List"
items:
  - apiVersion: "v1"
    kind: "PersistentVolumeClaim"
    metadata:
      name: "te-pv-jenkins-claim"
      namespace: "taf-te"
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 700Mi

  - apiVersion: "v1"
    kind: "PersistentVolumeClaim"
    metadata:
      name: "te-logs-claim"
      namespace: "taf-te"
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 800Mi

