/**
 * This class is generated by jOOQ
 */
package com.ericsson.cifwk.taf.metrics.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SampleData extends org.jooq.impl.TableImpl<com.ericsson.cifwk.taf.metrics.jooq.tables.records.SampleDataRecord> {

	private static final long serialVersionUID = -1440308606;

	/**
	 * The singleton instance of <code>taf_performance.sample_data</code>
	 */
	public static final com.ericsson.cifwk.taf.metrics.jooq.tables.SampleData SAMPLE_DATA = new com.ericsson.cifwk.taf.metrics.jooq.tables.SampleData();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.ericsson.cifwk.taf.metrics.jooq.tables.records.SampleDataRecord> getRecordType() {
		return com.ericsson.cifwk.taf.metrics.jooq.tables.records.SampleDataRecord.class;
	}

	/**
	 * The column <code>taf_performance.sample_data.id</code>.
	 */
	public final org.jooq.TableField<com.ericsson.cifwk.taf.metrics.jooq.tables.records.SampleDataRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>taf_performance.sample_data.request_body</code>.
	 */
	public final org.jooq.TableField<com.ericsson.cifwk.taf.metrics.jooq.tables.records.SampleDataRecord, java.lang.String> REQUEST_BODY = createField("request_body", org.jooq.impl.SQLDataType.CLOB.length(65535), this, "");

	/**
	 * The column <code>taf_performance.sample_data.request_headers</code>.
	 */
	public final org.jooq.TableField<com.ericsson.cifwk.taf.metrics.jooq.tables.records.SampleDataRecord, java.lang.String> REQUEST_HEADERS = createField("request_headers", org.jooq.impl.SQLDataType.CLOB.length(65535), this, "");

	/**
	 * The column <code>taf_performance.sample_data.response_body</code>.
	 */
	public final org.jooq.TableField<com.ericsson.cifwk.taf.metrics.jooq.tables.records.SampleDataRecord, java.lang.String> RESPONSE_BODY = createField("response_body", org.jooq.impl.SQLDataType.CLOB.length(65535), this, "");

	/**
	 * The column <code>taf_performance.sample_data.response_headers</code>.
	 */
	public final org.jooq.TableField<com.ericsson.cifwk.taf.metrics.jooq.tables.records.SampleDataRecord, java.lang.String> RESPONSE_HEADERS = createField("response_headers", org.jooq.impl.SQLDataType.CLOB.length(65535), this, "");

	/**
	 * The column <code>taf_performance.sample_data.sample_id</code>.
	 */
	public final org.jooq.TableField<com.ericsson.cifwk.taf.metrics.jooq.tables.records.SampleDataRecord, java.lang.Long> SAMPLE_ID = createField("sample_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * Create a <code>taf_performance.sample_data</code> table reference
	 */
	public SampleData() {
		this("sample_data", null);
	}

	/**
	 * Create an aliased <code>taf_performance.sample_data</code> table reference
	 */
	public SampleData(java.lang.String alias) {
		this(alias, com.ericsson.cifwk.taf.metrics.jooq.tables.SampleData.SAMPLE_DATA);
	}

	private SampleData(java.lang.String alias, org.jooq.Table<com.ericsson.cifwk.taf.metrics.jooq.tables.records.SampleDataRecord> aliased) {
		this(alias, aliased, null);
	}

	private SampleData(java.lang.String alias, org.jooq.Table<com.ericsson.cifwk.taf.metrics.jooq.tables.records.SampleDataRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.ericsson.cifwk.taf.metrics.jooq.TafPerformance.TAF_PERFORMANCE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.ericsson.cifwk.taf.metrics.jooq.tables.records.SampleDataRecord, java.lang.Long> getIdentity() {
		return com.ericsson.cifwk.taf.metrics.jooq.Keys.IDENTITY_SAMPLE_DATA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.ericsson.cifwk.taf.metrics.jooq.tables.records.SampleDataRecord> getPrimaryKey() {
		return com.ericsson.cifwk.taf.metrics.jooq.Keys.KEY_SAMPLE_DATA_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.ericsson.cifwk.taf.metrics.jooq.tables.records.SampleDataRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.ericsson.cifwk.taf.metrics.jooq.tables.records.SampleDataRecord>>asList(com.ericsson.cifwk.taf.metrics.jooq.Keys.KEY_SAMPLE_DATA_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.ericsson.cifwk.taf.metrics.jooq.tables.records.SampleDataRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.ericsson.cifwk.taf.metrics.jooq.tables.records.SampleDataRecord, ?>>asList(com.ericsson.cifwk.taf.metrics.jooq.Keys.FK_SAMPLE_DATA_SAMPLES1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.ericsson.cifwk.taf.metrics.jooq.tables.SampleData as(java.lang.String alias) {
		return new com.ericsson.cifwk.taf.metrics.jooq.tables.SampleData(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.ericsson.cifwk.taf.metrics.jooq.tables.SampleData rename(java.lang.String name) {
		return new com.ericsson.cifwk.taf.metrics.jooq.tables.SampleData(name, null);
	}
}
