/**
 * This class is generated by jOOQ
 */
package com.ericsson.cifwk.taf.metrics.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TestCases extends org.jooq.impl.TableImpl<com.ericsson.cifwk.taf.metrics.jooq.tables.records.TestCasesRecord> {

	private static final long serialVersionUID = -40662356;

	/**
	 * The singleton instance of <code>taf_performance.test_cases</code>
	 */
	public static final com.ericsson.cifwk.taf.metrics.jooq.tables.TestCases TEST_CASES = new com.ericsson.cifwk.taf.metrics.jooq.tables.TestCases();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.ericsson.cifwk.taf.metrics.jooq.tables.records.TestCasesRecord> getRecordType() {
		return com.ericsson.cifwk.taf.metrics.jooq.tables.records.TestCasesRecord.class;
	}

	/**
	 * The column <code>taf_performance.test_cases.id</code>.
	 */
	public final org.jooq.TableField<com.ericsson.cifwk.taf.metrics.jooq.tables.records.TestCasesRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>taf_performance.test_cases.name</code>.
	 */
	public final org.jooq.TableField<com.ericsson.cifwk.taf.metrics.jooq.tables.records.TestCasesRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>taf_performance.test_cases.test_suite_id</code>.
	 */
	public final org.jooq.TableField<com.ericsson.cifwk.taf.metrics.jooq.tables.records.TestCasesRecord, java.lang.Long> TEST_SUITE_ID = createField("test_suite_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * Create a <code>taf_performance.test_cases</code> table reference
	 */
	public TestCases() {
		this("test_cases", null);
	}

	/**
	 * Create an aliased <code>taf_performance.test_cases</code> table reference
	 */
	public TestCases(java.lang.String alias) {
		this(alias, com.ericsson.cifwk.taf.metrics.jooq.tables.TestCases.TEST_CASES);
	}

	private TestCases(java.lang.String alias, org.jooq.Table<com.ericsson.cifwk.taf.metrics.jooq.tables.records.TestCasesRecord> aliased) {
		this(alias, aliased, null);
	}

	private TestCases(java.lang.String alias, org.jooq.Table<com.ericsson.cifwk.taf.metrics.jooq.tables.records.TestCasesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.ericsson.cifwk.taf.metrics.jooq.TafPerformance.TAF_PERFORMANCE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.ericsson.cifwk.taf.metrics.jooq.tables.records.TestCasesRecord> getPrimaryKey() {
		return com.ericsson.cifwk.taf.metrics.jooq.Keys.KEY_TEST_CASES_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.ericsson.cifwk.taf.metrics.jooq.tables.records.TestCasesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.ericsson.cifwk.taf.metrics.jooq.tables.records.TestCasesRecord>>asList(com.ericsson.cifwk.taf.metrics.jooq.Keys.KEY_TEST_CASES_PRIMARY, com.ericsson.cifwk.taf.metrics.jooq.Keys.KEY_TEST_CASES_NAME_UNIQUE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.ericsson.cifwk.taf.metrics.jooq.tables.records.TestCasesRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.ericsson.cifwk.taf.metrics.jooq.tables.records.TestCasesRecord, ?>>asList(com.ericsson.cifwk.taf.metrics.jooq.Keys.FK_TEST_CASES_TEST_SUITES1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.ericsson.cifwk.taf.metrics.jooq.tables.TestCases as(java.lang.String alias) {
		return new com.ericsson.cifwk.taf.metrics.jooq.tables.TestCases(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.ericsson.cifwk.taf.metrics.jooq.tables.TestCases rename(java.lang.String name) {
		return new com.ericsson.cifwk.taf.metrics.jooq.tables.TestCases(name, null);
	}
}
