version: '2.1'

# Start TE based on docker images from docker registry, Allure report will be hosted locally on https://${HOSTNAME}:443 and http://${HOSTNAME}:8088
# Note: No image will be built, all images will be downloaded if not already available locally.
# Note: Don't forget to set the following environment variables if you are not using the "dockerized_te.sh script:
#       HOSTNAME          e.g. 'export HOSTNAME=159.107.166.146'
#       EXECUTOR_COUNT    e.g. 'export EXECUTOR_COUNT=4'
#       MAVEN_OFFLINE     e.g. 'export MAVEN_OFFLINE=true'

services:
  taf_te_message_bus:
    image: taf_te_message_bus:${project.version}
    container_name: "taf_te_messagebus"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    logging:
      options:
        max-size: "1g"
        max-file: "2"
  taf_te_master:
    image: taf_te_master:${project.version}
    container_name: "taf_te_master"
    ports:
      - "50000:50000"
      - "8080:8080"
      - "8443:443"
    command: --prefix=/jenkins/ --hostname=${HOSTNAME} --external-jenkins-address=http://${HOSTNAME}:8080/jenkins/ --local-report-host-base-uri=http://${HOSTNAME}:8088 --allure_service_url=http://${HOSTNAME}:8088/api/reports --allure_service_backend_url=http://${HOSTNAME}:8000 --turn-off-reporting=true
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/log/te_logs:/var/log/te_logs
    logging:
      options:
        max-size: "1g"
        max-file: "2"
    depends_on:
      - taf_te_message_bus
    environment:
        - ENABLE_LDAP=true
    links:
      - "taf_ldap:enmteagat"
  taf_te_slave1:
    image: taf_te_slave:${project.version}
    container_name: "taf_te_slave1"
    command: --te-master-address=http://${HOSTNAME}:8080/jenkins/ --executor-count=${EXECUTOR_COUNT} --create-jenkins-node=true --agent-name=taf_te_slave_jnlp-1 --maven-offline=${MAVEN_OFFLINE} --te-username=${TE_USERNAME} --te-password=${TE_PASSWORD}
    environment:
      - ENABLE_LDAP=true
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/log/te_logs:/var/log/te_logs
      - /root/.m2/repository:/root/.m2/repository:ro
      - /root/testdata:/root/testdata
    logging:
      options:
        max-size: "1g"
        max-file: "2"
    depends_on:
      - taf_te_master
  backend:
    image: allure-service:${allure-service.version}
    container_name: "taf_te_allure_backend"
    ports:
      - "8000:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - spring.cloud.config.failFast=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      retries: 3
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/log/allure-service:/var/log/allure-service
    logging:
      options:
        max-size: "1g"
        max-file: "2"
  allure_service_nginx:
    image: allure-nginx:${allure-service.version}
    container_name: "taf_te_allure_nginx"
    environment:
      - HOSTNAME=${HOSTNAME}
      - ENABLE_LDAP=true
    ports:
      - "8088:80"
      - "443:443"
    healthcheck:
      test: ["CMD", "ping", "-c1", "localhost"]
      interval: 20s
      retries: 3
    depends_on:
      - "backend"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/log/te_logs:/usr/share/nginx/html:ro
      - /var/log/te_logs:/usr/local/nginx/html:ro
    logging:
      options:
        max-size: "1g"
        max-file: "2"
  TDM_backend:
    image: tdm-server:${tdm.version}
    container_name: "TDM_backend"
    restart: "always"
    ports:
      - "9443:8888"
      - "8082:8444"
    environment:
      - SPRING_PROFILES_ACTIVE=customer
    volumes:
      - /opt/store/volumes/tdm-logs:/var/log/tdm
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - mongodb
    logging:
      options:
        max-size: "1g"
        max-file: "3"
    links:
      - "taf_ldap:enmteagat"
  mongodb:
    image: mongo:3.2
    restart: "always"
    ports:
     - "27017:27017"
    volumes:
     - /tdmMongoDB/db:/data/db
     - /etc/timezone:/etc/timezone:ro
     - /etc/localtime:/etc/localtime:ro
  taf_ldap:
    image:  taf_ldap:${project.version}
    container_name: "taf_ldap"
    ports:
      - "3689:389"
    volumes:
      - /etc/openldap:/etc/ldap
      - /var/lib/ldap/:/var/lib/ldap
      - /etc/ldap/prepopulate/:/etc/ldap.dist/prepopulate
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
  taf_aat:
    image: taf_aat:${project.version}
    container_name: "taf_aat"
    ports:
      - "5000:5000"
    volumes:
      - /root/agat:/root/agat
      - /var/tmp/aat_execution:/var/tmp/aat_execution